[project]
name = "globaldetective"
version = "0.1.0"
description = "Global Detective Quest"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.4",
    "gunicorn>=23.0.0",
]
